export const ProfileValidationError = {
    AGE: 'INCORRECT_AGE',
    AVATAR_LINK: 'INCORRECT_AVATAR_LINK',
    EMAIL: 'INCORRECT_EMAIL',
    FIRSTNAME: 'INCORRECT_FIRSTNAME',
    LASTNAME: 'INCORRECT_LASTNAME',
    USERNAME: 'INCORRECT_USERNAME',
} as const;
