name: Frontend test CI

on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]

jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 17.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Staring Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install modules
                run: npm install

            -   name: Build production project
                run: npm run build:prod
                if: always()

            -   name: Linting typescript
                run: npm run lint:ts
                if: always()

            -   name: Linting css
                run: npm run lint:scss
                if: always()

            -   name: Testing
                run: npm run test
                if: always()

            -   name: Telegram notification
                if: always()
                uses: appleboy/telegram-action@master
                with:
                    to: ${{ secrets.TELEGRAM_CHAT_ID }}
                    token: ${{ secrets.TELEGRAM_TOKEN }}
                    message: |
                        ${{ github.actor }} created commit: ${{ github.event.commits[0].message }}

                        See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
